### ISSUE TITLE
help

### ISSUE THREAD

**Issue by dkeng005** [twitter/twitter-text-java#78]
please help how i use integrate this library(twitter-text-java) in my project 
i mean how  and where in eclipse i use autolink.java regex.java , extractor.java , hithiglighter.java  ,validator.java programs ?

**Comment by caniszczyk** [comment]
This is available as a Maven dependency:
https://github.com/twitter/twitter-text/blob/master/java/README.md#getting-started

Just add the library to your pom.xml and within Eclipse, make sure you have the Eclipse Maven Tools (M2E) installed and you should be good to go.
